version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: kcbear/spring-boot-rest:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.7"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet: